### ISSUE TITLE
Incorrect bulkheadProfiles

### ISSUE THREAD

**Issue by Strych74** [AstroWell/Knes#25]
I've picked up what I think may be a couple of errors with the bulkheadProfile values in the part cfg files, as follows:

_Knes_Vesta_FuelTank_0625_3125
bulkheadProfiles = size00  (this is a 0.625m tank, should be size0)

_Knes_Mireille_LFO_short_09375
_Knes_Mireille_LFO_medium_09375
_Knes_Mireille_LFO_long_09375
_Knes_Nano_Cryo_FuelTank_09375
_Knes_Small_Cryo_FuelTank_09375
bulkheadProfiles = size1  (these are all 0.9375m tanks, should be size0p5)

Knes_Catherine_Adapter_Quad_1875
bulkheadProfiles = size1p5  (connects 1.25m to 1.875m parts, should be bulkheadProfiles = size1p5,size1)

Knes_Catherine_Adapter_Quad_250
bulkheadProfiles = size1p5  (connects 1.25m to 2.5m parts, should be bulkheadProfiles = size1,size2)

**Comment by AstroWell** [comment]
fixed
